global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s

  # Golang App expose `/metrics` endpoint
  - job_name: 'exchange-app'
    static_configs:
      - targets: ['exg:8080']
    metrics_path: '/metrics'
    scrape_interval: 15s